// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Domain.Pump", b =>
                {
                    b.Property<Guid>("PumpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PumpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PumpName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PumpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PumpType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PumpId");

                    b.ToTable("Pumps");
                });
#pragma warning restore 612, 618
        }
    }
}
